### ISSUE TITLE
(uYouPlus TrollStore) VP9 randomly stops working

### ISSUE THREAD

**Issue by gototheskinny** [PoomSmart/YTUHD#12]
Device: iPhone 12 w/ios15.0 

When you're not watching in 1440p or 4k(these resolutions only have vp9 or av1 coded versions) randomly video turns into h264 avc! 
Can you please look into this issue?

**Comment by PoomSmart** [comment]
Will be fixed in version 1.2.10

**Comment by gototheskinny** [comment]
Thank you!
