### ISSUE TITLE
[Enhancement] Way to only enable with resolutions > 1080p

### ISSUE THREAD

**Issue by AuroraWright** [PoomSmart/YTUHD#35]
Right now, as I saw from the "stats for nerds", VP9 is toggled globally. I think it would be ideal for jailed devices if there was an additional toggle to enable VP9 only when 2/4K are selected, not sure if it's feasible but this way one could keep 1080p (h264) as default to reduce battery usage, and select a higher resolution only when needed (e.g. when watching something in full screen).

**Comment by augustobob** [comment]
Adding to this issue, when vp9 is enabled it’s impossible to fetch the video to download in mp4 with uyou. Also it looks like my device is using cpu decoding when vp9 is enabled even it supporting (the entitlement restriction).

**Comment by PoomSmart** [comment]
Done in version 1.4.0

**Comment by AuroraWright** [comment]
Thanks, works perfectly

**Comment by augustobob** [comment]
Thanks Poom, you’re helping me deal with my unjb phone
