### ISSUE TITLE
[Question] About the hardware decode AV1 formate in a17 chips

### ISSUE THREAD

**Issue by checkpoint1112** [PoomSmart/YTUHD#36]
A17 pro is udated AV1 codec decode. Can we unlock av1 codec video when using YTUHD. Let the new iphone can use the hardware decode for saving battery.

**Comment by PoomSmart** [comment]
That might only be possible if YouTube started serving AV1 codec to end users.

**Comment by checkpoint1112** [comment]
> That might only be possible if YouTube started serving AV1 codec to end users.

Sorry, I recently discovered that the original YouTube started to push the av01 format to the iPhone 15 pro series. I wonder if I can add only the av1 and avc formats to the YTUHD project to save power?
![IMG_9770](https://github.com/PoomSmart/YTUHD/assets/126166082/47945169-aa00-4b61-be9e-bec36bd19607)
