### ISSUE TITLE
VP9 not enabled for quality under 1440p

### ISSUE THREAD

**Issue by SuperAmirhamza** [PoomSmart/YTUHD#38]
![image](https://github.com/PoomSmart/YTUHD/assets/45406543/29299ff2-b0b9-4de3-96c9-8be5df61a947)

**Comment by SuperAmirhamza** [comment]
Please fix this it was working fine in uyouplus version 18.14.1 and prior and afterwards it's stopped working

**Comment by PoomSmart** [comment]
VP9 is intentionally for 1440p+ because it unnecessarily consumes more battery.

https://github.com/PoomSmart/YTUHD/issues/35

**Comment by haomuch** [comment]
> VP9 is intentionally for 1440p+ because it unnecessarily consumes more battery.
> 
> #35

iOS devices with VP9 hardware decoding capability should not consume much more battery for VP9 video. The vanilla YouTube app from Appstore already enables VP9 codec for all resolutions on qualified iOS devices. Could you please enable VP9 for all resolutions? At least provide a option?

**Comment by PoomSmart** [comment]
Implemented in v1.5.0
