### ISSUE TITLE
Stuttering 

### ISSUE THREAD

**Issue by iMonZ** [PoomSmart/YTUHD#4]
Currently I’m experiencing huge stuttering on my iPhone 12 Pro Max when I Switch to 2160p.

**Comment by PoomSmart** [comment]
This is hardly due to YTUHD. It's either YouTube's VP9 decoder isn't robust enough or your device just can't handle it or your network connection is poor.

**Comment by iMonZ** [comment]
> This is hardly due to YTUHD. It's either YouTube's VP9 decoder isn't robust enough or your device just can't handle it or your network connection is poor.

I would say that my device has enough power for that! And the network connection is good enough for game streaming.
But I’m not the only person experiencing that problem

**Comment by PoomSmart** [comment]
@iMonZ If you insist on that, how about you check Stats for nerds on the video you are playing and take the screenshot of the information you see.

**Comment by iMonZ** [comment]
> @iMonZ If you insist on that, how about you check Stats for nerds on the video you are playing and take the screenshot of the information you see.

All right!
Here is the screenshot while it stutters:

https://ibb.co/XJh296F

And while I viewed the Nerd stats, I see that it switches between playback and buffering pretty quick, as you can see in this video:
https://ufile.io/wpf6kh1s

But when I reduce the resolution from 4k, it works fine again.

I don't think that the A14 has problems with 4K VP9 Video material.

**Comment by PoomSmart** [comment]
It could be that A14 has issues with VP9. I tested this on my iPad Pro 11" (2018) that has A12X chip and the 4K video plays without stutters whatsoever. This may be iOS version thing. Maybe Apple will fix this eventually if even on iOS 14.6/14.7/15.0b2 it still stutters.

**Comment by iMonZ** [comment]
> It could be that A14 has issues with VP9. I tested this on my iPad Pro 11" (2018) that has A12X chip and the 4K video plays without stutters whatsoever. This may be iOS version thing. Maybe Apple will fix this eventually if even on iOS 14.6/14.7/15.0b2 it still stutters.

Hm strange
I tried it with 14.4, 14.5, 14.6 and 15b2
