### ISSUE TITLE
Enabling VP9 leads to crashes.

### ISSUE THREAD

**Issue by eyeslow** [PoomSmart/YTUHD#45]
I've sideloaded YTLite 4.0.1 on 19.22.6 which worked fine a few hours ago with YTUHD enabled. I've tried to disable all other tweaks to sort out the problem and found out its YTUHD. Only selected option was "Enable VP9" - not "VP9 for all".

Device: 15 Pro Max
OS: 17.5.1

Crash Log:
[YouTube-2024-06-10-155237.txt](https://github.com/user-attachments/files/15774522/YouTube-2024-06-10-155237.txt)

**Comment by eyeslow** [comment]
Crash Log with translated report as .txt:
[YouTube-2024-06-10-193218.txt](https://github.com/user-attachments/files/15777245/YouTube-2024-06-10-193218.txt)

**Comment by PoomSmart** [comment]
Are you sure the YTUHD instance inside YTLite IPA is the latest version?

**Comment by eyeslow** [comment]
> Are you sure the YTUHD instance inside YTLite IPA is the latest version?

No actually i'm not, YTLite came with YTUHD pre-installed. Would have to ask @dayanch96 about that.

**Comment by dayanch96** [comment]
Hey @eyeslow, please do not bother devs with issues not related to their tweak if you are not sure about source of the issue. in YTLite ipa was previous version of the YTUHD

**Comment by eyeslow** [comment]
Got it, sorry about that @PoomSmart. Your releases are so up-to-date almost anytime, so I just assumed it was the latest version, please see this a compliment @dayanch96.
