### ISSUE TITLE
Doesn’t work sideloaded

### ISSUE THREAD

**Issue by gh0sti** [PoomSmart/YTUHD#5]
Yesterday I sideloaded latest YouTube with cercube tweak and YTUHD tweak. I could stream 4K. However this morning I can't switch to 4K or 1440p. I tried enabling 1440p in cercube settings and highest stream in YouTube settings. How can I help trouble shoot this?

iOS 14.7 release and iPhone 11 Pro Max. 

Also is there a way for cercube settings to have 4K as a forced stream toggle?

**Comment by gh0sti** [comment]
Its the one provided here. It's bundled with several other tweaks to sideloaded. 

https://www.dropbox.com/s/ycxao891voxo7ul/Better%20Cercube%2016.28.2%20%285.2.28%29%20%26%20iSponsorBlock%201.0-10%20%26%20YTDisableSuggestions%20%26%20YTClassicVideoQuality%20%26%20YTNoShorts%20%26%20YouAreThere%20%26%20YTSystemAppearance%20%26%20YTUHD%20%26%20YouPiP%20-%20Qn_.ipa?dl=0

**Comment by PoomSmart** [comment]
Should be fixed as of now.
